import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="image" href="favicon.ico" />
            </Head>

            <header className={styles.header}>
                <Link href="https://www.symbio.one/">
                    <Image
                        src="/logo1.png"
                        alt="Logo"
                        width={250}
                        height={120}
                    />
                </Link>
                <div className={styles.bar}>
                    <Link href=".." className={styles.buttons}>
                        <h1>ACCUEIL</h1>
                    </Link>
                    <Link href="system" className={styles.buttons}>
                        <h1>
                            CONTRÔLE
                            <br />
                            -
                            <br />
                            COMMANDE
                        </h1>
                    </Link>
                    <Link href="about" className={styles.buttons}>
                        <h1>ANNEXES</h1>
                    </Link>
                    <Link href="about_us" className={styles.buttons}>
                        <h1>NOTRE GROUPE</h1>
                    </Link>
                </div>
            </header>

            <main className={styles.main}>
                <br />
                <h1 className={styles.title}>
                    Projet industrie sur la PàC à hydrogène
                </h1>
                <Link href="system" className={styles.card}>
                    <h2 className={styles.sous_title}>CONTRÔLE-COMMANDE</h2>
                    <p className={styles.card_desc}>
                        &rarr; Afficher les mesures des capteurs <br />
                        &rarr; Contrôler les électrovannes
                    </p>
                </Link>
                <br />
                <h2 className={styles.sous_title}>DESCRIPTION DU PROJET</h2>
                <p className={styles.description}>
                    &nbsp;&nbsp;&nbsp;Notre projet s'intitule "Montage et
                    exploitation d'un banc d'essai avec une pile à combustible à
                    hydrogène pour la recharge de batteries de robots" et a pour
                    objectif de développer un système de recharge autonome, via
                    PàC H2, du robot SCAR de Boston Dynamics. Il s'agit d'un
                    projet en collaboration avec l'entreprise Symbio, leader
                    mondial de la mobilité hydrogène, et avec l'IJL, laboratoire
                    de recherche en science des matériaux.
                </p>
                <Link href="about" className={styles.card}>
                    <h2 className={styles.sous_title}>ANNEXES</h2>
                    <p className={styles.card_desc}>
                        &rarr; Accéder à notre vidéo "Mon projet industrie en
                        180s"
                        <br />
                        &rarr; Accéder à notre rapport de projet
                    </p>
                </Link>
            </main>

            <footer className={styles.footer}>
                <Link href="about_us">
                    Membres du groupe :{" "}
                    <b className={styles.noms}>
                        &nbsp;CORCORAL Erwan / ROCH Valentin / SALHI Thomas /
                        THELLIER Elie
                    </b>
                </Link>
            </footer>
        </div>
    );
}
